# 指定运行环境
language: node_js

# 指定nodejs版本，可以指定多个
node_js:
  - 11.2.0

# Node 项目的install和script阶段都有默认脚本，可以省略
# 运行的脚本命令
# script:
#   - npm run ci

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

# 部署到 Github Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master